language: haskell
ghc: 
  - 7.8
install:
  - cabal install --only-dependencies --enable-tests --reorder-goals
script:
  - cabal configure --enable-tests --enable-coverage
  - cabal build
  - cabal test
after_script:
  - cabal install hpc-coveralls
  - hpc-coveralls --exclude-dir=tests --exclude-dir=src/lib --display-report
